# compatible is the version number of the configuration (topic names, params...)
# currently mcl_3dl has two (0 and 1)
compatible: 1

map_frame: "map"
odom_frame: "odom"
robot_frame: "base_link"
accum_cloud: 2
fake_imu: true # if there is no imu
fake_odom: false # if there is no odom
lpf_step: 1.0
num_particles: 128
resample_var_yaw: 0.05
resample_var_pitch: 0.1
resample_var_roll: 0.1
acc_var: 1.2
likelihood:
  match_dist_min: 0.3
  match_output_dist: 0.3
